machine_type = ENV["HOMEBREW_MACHINE_TYPE"]

# Core tools — all platforms
brew "bat"
brew "eza"
brew "btop"
brew "fd"
brew "fzf"
brew "gh"
brew "git-lfs"
brew "gnupg"
brew "htop"
brew "jq"
brew "lazygit"
brew "mise"
brew "neovim"
brew "nmap"
brew "pv"
brew "ripgrep"
brew "rtk"
brew "starship"
brew "thefuck"
brew "tmux"
brew "tmuxp"
brew "watch"
brew "wget"
brew "zoxide"

brew "duckdb"
cask "codex"
brew "opencode"
brew "pi-coding-agent"

# macOS only
if OS.mac?
  tap "felixkratz/formulae"
  tap "nikitabobko/tap"
  tap "barutsrb/tap"
  tap "manaflow-ai/cmux"

  # WM / bar
  brew "felixkratz/formulae/sketchybar"
  cask "nikitabobko/tap/aerospace"
  cask "barutsrb/tap/omniwm"

  # Terminal / editor
  cask "ghostty"

  # Dev tools
  cask "bruno"
  cask "claude"
  cask "ngrok"
  cask "docker-desktop"

  # Apps
  cask "obsidian"
  cask "spotify"
  cask "lm-studio"
  cask "caffeine"
  cask "raycast"
  cask "cmux"
  cask "stats"

  # Work Apps
  if machine_type == "work"
    cask "granola"
    cask "wispr-flow"

    # Database
    brew "libpq"
    brew "pgformatter"
    brew "postgresql@18", restart_service: :changed, link: true
  end

  if machine_type == "personal"
    cask "1password"
    cask "1password-cli"
    cask "brave-browser"
    brew "tailscale"
  end

end
