## TPM
# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'christoomey/vim-tmux-navigator'

# bootstrap
if "test ! -d ~/.local/share/tmux/plugins/tpm" \
    "run 'mkdir -p ~/.local/share/tmux/plugins && git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm && ~/.local/share/tmux/plugins/tpm/bin/install_plugins'"

# Set prefix to Ctrl-Space
unbind C-b
set -g prefix C-Space
bind Space send-prefix

# use vi keys
setw -g mode-keys vi

set -g default-shell $SHELL
set -g default-terminal "screen-256color"
set -g history-limit 50000
set -g renumber-windows on
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."
setw -g automatic-rename

bind-key C-a last-window
set -g base-index 1
set -s escape-time 0
setw -g aggressive-resize on
bind-key a send-prefix

setw -g monitor-activity on
set -g visual-activity on
set -g mouse off

bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"
bind-key C-x setw synchronize-panes

bind -n M-c new-window -c "#{pane_current_path}"
bind -n M-p previous-window
bind -n M-n next-window

# Copy/Paste
if-shell 'uname | grep -q Darwin' \
    'bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"' \
    'bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"'

# Navigate panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Resize panes
bind -n M-H resize-pane -L 2
bind -n M-J resize-pane -D 2
bind -n M-K resize-pane -U 2
bind -n M-L resize-pane -R 2

# Mark/Unmark panes
bind -n M-m select-pane -m
bind -n M-M select-pane -M

# Pane layouts
bind -n M-a select-layout main-vertical
bind -n M-A select-layout main-horizontal
bind -n M-E select-layout even-vertical
bind -n M-V select-layout even-horizontal

# Misc panes
bind -n M-z resize-pane -Z
bind-key ! break-pane
bind -n M-< join-pane

# Rotate window
bind -n M-O rotate-window

# Splits
bind-key v split-window -h
bind-key b split-window
bind -n M-s split-window -c "#{pane_current_path}"
bind -n M-v split-window -h -c "#{pane_current_path}"
bind -n M-x kill-pane

bind-key -r < swap-window -t -1
bind-key -r > swap-window -t +1

# Status Bar
set -g status-style bg=default
set -g status-fg "#a9b1d7"
set -g status-position bottom
set -g status-interval 1
set -g status-justify centre
set -g status-left-length 0
set -g status-right-length 0
set -g status-left "#S"
set -g status-right '#{prefix_highlight}'

# Popups
bind g display-popup -h 90% -w 90% -d "#{pane_current_path}" -E "lazygit"
bind Space display-popup -E "tmux new-session -A -s scratch"
# bind s display-popup -E -d "#{pane_current_path}" "git status && sleep 5" # show git status
# bind s run-shell ~/.config/tmux/scripts/tmux-session-menu
bind s display-popup -h 75% -w 90% -E "\
    tmux list-sessions -F '#{?session_attached,,#{session_name}}' |\
    sed '/^$/d' |\
    fzf --reverse --header jump-to-session --preview 'tmux capture-pane -pt {}'  |\
    xargs tmux switch-client -t"

run '~/.local/share/tmux/plugins/tpm/tpm'
