session_name: casecurity
start_directory: ~/src/github.com/bhoman-ca/casecurity

windows:
  - window_name: ai
    panes:
      - pane
  - window_name: code
    panes:
      - pane
  - window_name: infra
    panes:
      - pane
  - window_name: docker
    panes:
      - pane
